/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type PostFile200Response struct {

	Id string `json:"id,omitempty"`
}

// AssertPostFile200ResponseRequired checks if the required fields are not zero-ed
func AssertPostFile200ResponseRequired(obj PostFile200Response) error {
	return nil
}

// AssertRecursePostFile200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PostFile200Response (e.g. [][]PostFile200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePostFile200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPostFile200Response, ok := obj.(PostFile200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPostFile200ResponseRequired(aPostFile200Response)
	})
}
