/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetIonisationMethod200Response struct {

	Ionisation string `json:"ionisation,omitempty"`
}

// AssertGetIonisationMethod200ResponseRequired checks if the required fields are not zero-ed
func AssertGetIonisationMethod200ResponseRequired(obj GetIonisationMethod200Response) error {
	return nil
}

// AssertRecurseGetIonisationMethod200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetIonisationMethod200Response (e.g. [][]GetIonisationMethod200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetIonisationMethod200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetIonisationMethod200Response, ok := obj.(GetIonisationMethod200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetIonisationMethod200ResponseRequired(aGetIonisationMethod200Response)
	})
}
