/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetScansData200Response struct {
	Scans []int64 `json:"scans,omitempty"`
}

// AssertGetScansData200ResponseRequired checks if the required fields are not zero-ed
func AssertGetScansData200ResponseRequired(obj GetScansData200Response) error {
	return nil
}

// AssertRecurseGetScansData200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetScansData200Response (e.g. [][]GetScansData200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetScansData200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetScansData200Response, ok := obj.(GetScansData200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetScansData200ResponseRequired(aGetScansData200Response)
	})
}
