/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetFileName200Response struct {

	Filename string `json:"filename,omitempty"`
}

// AssertGetFileName200ResponseRequired checks if the required fields are not zero-ed
func AssertGetFileName200ResponseRequired(obj GetFileName200Response) error {
	return nil
}

// AssertRecurseGetFileName200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetFileName200Response (e.g. [][]GetFileName200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetFileName200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetFileName200Response, ok := obj.(GetFileName200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetFileName200ResponseRequired(aGetFileName200Response)
	})
}
