/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetInstrumentModel200Response struct {

	Model string `json:"model,omitempty"`
}

// AssertGetInstrumentModel200ResponseRequired checks if the required fields are not zero-ed
func AssertGetInstrumentModel200ResponseRequired(obj GetInstrumentModel200Response) error {
	return nil
}

// AssertRecurseGetInstrumentModel200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetInstrumentModel200Response (e.g. [][]GetInstrumentModel200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetInstrumentModel200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetInstrumentModel200Response, ok := obj.(GetInstrumentModel200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetInstrumentModel200ResponseRequired(aGetInstrumentModel200Response)
	})
}
