/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetScanPeaks200Response struct {

	Peaks []float32 `json:"peaks,omitempty"`
}

// AssertGetScanPeaks200ResponseRequired checks if the required fields are not zero-ed
func AssertGetScanPeaks200ResponseRequired(obj GetScanPeaks200Response) error {
	return nil
}

// AssertRecurseGetScanPeaks200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetScanPeaks200Response (e.g. [][]GetScanPeaks200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetScanPeaks200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetScanPeaks200Response, ok := obj.(GetScanPeaks200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetScanPeaks200ResponseRequired(aGetScanPeaks200Response)
	})
}
