/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetChromatogramCount200Response struct {
	ChromatogramCount int64 `json:"chromatogramCount,omitempty"`
}

// AssertGetChromatogramCount200ResponseRequired checks if the required fields are not zero-ed
func AssertGetChromatogramCount200ResponseRequired(obj GetChromatogramCount200Response) error {
	return nil
}

// AssertRecurseGetChromatogramCount200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetChromatogramCount200Response (e.g. [][]GetChromatogramCount200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetChromatogramCount200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetChromatogramCount200Response, ok := obj.(GetChromatogramCount200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetChromatogramCount200ResponseRequired(aGetChromatogramCount200Response)
	})
}
