/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetSoftware200Response struct {

	Software string `json:"software,omitempty"`
}

// AssertGetSoftware200ResponseRequired checks if the required fields are not zero-ed
func AssertGetSoftware200ResponseRequired(obj GetSoftware200Response) error {
	return nil
}

// AssertRecurseGetSoftware200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetSoftware200Response (e.g. [][]GetSoftware200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetSoftware200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetSoftware200Response, ok := obj.(GetSoftware200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetSoftware200ResponseRequired(aGetSoftware200Response)
	})
}
