/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetScanPeakCount200Response struct {

	PeakCount int32 `json:"peakCount,omitempty"`
}

// AssertGetScanPeakCount200ResponseRequired checks if the required fields are not zero-ed
func AssertGetScanPeakCount200ResponseRequired(obj GetScanPeakCount200Response) error {
	return nil
}

// AssertRecurseGetScanPeakCount200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetScanPeakCount200Response (e.g. [][]GetScanPeakCount200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetScanPeakCount200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetScanPeakCount200Response, ok := obj.(GetScanPeakCount200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetScanPeakCount200ResponseRequired(aGetScanPeakCount200Response)
	})
}
