/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code    int
	Headers map[string][]string
	Body    interface{}
}
