/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetSampleData200Response struct {
	Sample string `json:"sample,omitempty"`
}

// AssertGetSampleData200ResponseRequired checks if the required fields are not zero-ed
func AssertGetSampleData200ResponseRequired(obj GetSampleData200Response) error {
	return nil
}

// AssertRecurseGetSampleData200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetSampleData200Response (e.g. [][]GetSampleData200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetSampleData200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetSampleData200Response, ok := obj.(GetSampleData200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetSampleData200ResponseRequired(aGetSampleData200Response)
	})
}
