/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetInstrumentDetector200Response struct {
	Detector string `json:"detector,omitempty"`
}

// AssertGetInstrumentDetector200ResponseRequired checks if the required fields are not zero-ed
func AssertGetInstrumentDetector200ResponseRequired(obj GetInstrumentDetector200Response) error {
	return nil
}

// AssertRecurseGetInstrumentDetector200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetInstrumentDetector200Response (e.g. [][]GetInstrumentDetector200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetInstrumentDetector200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetInstrumentDetector200Response, ok := obj.(GetInstrumentDetector200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetInstrumentDetector200ResponseRequired(aGetInstrumentDetector200Response)
	})
}
