/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetInstrumentManufacturer200Response struct {
	Manufacturer string `json:"manufacturer,omitempty"`
}

// AssertGetInstrumentManufacturer200ResponseRequired checks if the required fields are not zero-ed
func AssertGetInstrumentManufacturer200ResponseRequired(obj GetInstrumentManufacturer200Response) error {
	return nil
}

// AssertRecurseGetInstrumentManufacturer200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetInstrumentManufacturer200Response (e.g. [][]GetInstrumentManufacturer200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetInstrumentManufacturer200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetInstrumentManufacturer200Response, ok := obj.(GetInstrumentManufacturer200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetInstrumentManufacturer200ResponseRequired(aGetInstrumentManufacturer200Response)
	})
}
