/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetIsolationWindows200Response struct {
	IsolationWindows []GetIsolationWindows200ResponseIsolationWindowsInner `json:"IsolationWindows,omitempty"`
}

// AssertGetIsolationWindows200ResponseRequired checks if the required fields are not zero-ed
func AssertGetIsolationWindows200ResponseRequired(obj GetIsolationWindows200Response) error {
	for _, el := range obj.IsolationWindows {
		if err := AssertGetIsolationWindows200ResponseIsolationWindowsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetIsolationWindows200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetIsolationWindows200Response (e.g. [][]GetIsolationWindows200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetIsolationWindows200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetIsolationWindows200Response, ok := obj.(GetIsolationWindows200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetIsolationWindows200ResponseRequired(aGetIsolationWindows200Response)
	})
}
