/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mzserver

type GetInstrumentAnalyzer200Response struct {
	Analyzer string `json:"analyzer,omitempty"`
}

// AssertGetInstrumentAnalyzer200ResponseRequired checks if the required fields are not zero-ed
func AssertGetInstrumentAnalyzer200ResponseRequired(obj GetInstrumentAnalyzer200Response) error {
	return nil
}

// AssertRecurseGetInstrumentAnalyzer200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetInstrumentAnalyzer200Response (e.g. [][]GetInstrumentAnalyzer200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetInstrumentAnalyzer200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetInstrumentAnalyzer200Response, ok := obj.(GetInstrumentAnalyzer200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetInstrumentAnalyzer200ResponseRequired(aGetInstrumentAnalyzer200Response)
	})
}
