/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	mzserver "github.com/uly55e5/mb-tools/openapi-server/src"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := mzserver.NewDefaultApiService()
	DefaultApiController := mzserver.NewDefaultApiController(DefaultApiService)

	router := mzserver.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
