// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// IndexListType is Index element containing one or more offsets for random data access for the entity described in the 'name' attribute.
type IndexListType struct {
	CountAttr int          `xml:"count,attr"`
	Index     []*IndexType `xml:"index"`
}

// IndexType is File pointer offset (in bytes) of the element identified by the 'id' attribute.
type IndexType struct {
	NameAttr string        `xml:"name,attr"`
	Offset   []*OffsetType `xml:"offset"`
}

// OffsetType ...
type OffsetType struct {
	IdRefAttr    string  `xml:"idRef,attr"`
	SpotIDAttr   string  `xml:"spotID,attr,omitempty"`
	ScanTimeAttr float64 `xml:"scanTime,attr,omitempty"`
	Value        int64   `xml:",chardata"`
}

// IndexedmzML ...
type IndexedmzML struct {
	XMLName         xml.Name       `xml:"indexedmzML"`
	DxMzML          *MzMLType      `xml:"dx:mzML"`
	IndexList       *IndexListType `xml:"indexList"`
	IndexListOffset int64          `xml:"indexListOffset"`
	FileChecksum    string         `xml:"fileChecksum"`
}
